apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-codex-assignment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DanielLuponenko/codex-assignment.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true